# Generated by Django 2.1.1 on 2018-09-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errortype',
            name='avg_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='max_value',
            field=models.FloatField(),
        ),
    ]
